export const queryKeys = {
    projects: ["projects"] as const,
    organizationProjects: (orgId: string) => ["organizations", orgId, "projects"] as const,
    project: (id: string) => ["projects", id] as const,
    projectAccess: (projectId: string) => ["projects", projectId, "access"] as const,
    projectWorkflows: (projectId: string) => ["projects", projectId, "workflows"] as const,
    workflows: ["workflows"] as const,
    workflowsUnfiled: ["workflows", "unfiled"] as const,
    workflow: (id: string) => ["workflows", id] as const,
    workflowAccess: (workflowId: string) => ["workflows", workflowId, "access"] as const,
    versions: (workflowId: string) => ["workflows", workflowId, "versions"] as const,
    snapshots: (workflowId: string) => ["workflows", workflowId, "snapshots"] as const,
    snapshot: (workflowId: string, snapshotId: string) => ["workflows", workflowId, "snapshots", snapshotId] as const,
    variables: (workflowId: string) => ["workflows", workflowId, "variables"] as const,
    pages: (workflowId: string) => ["pages", workflowId] as const,
    page: (id: string) => ["pages", "single", id] as const,
    workflowSteps: (workflowId: string) => ["steps", "workflow", workflowId] as const,
    steps: (pageId: string) => ["steps", pageId] as const,
    step: (id: string) => ["steps", "single", id] as const,
    blocks: (workflowId: string, phase?: string) => ["blocks", workflowId, phase] as const,
    transformBlocks: (workflowId: string) => ["transformBlocks", workflowId] as const,
    transformBlock: (id: string) => ["transformBlocks", id] as const,
    runs: (workflowId: string) => ["runs", workflowId] as const,
    run: (id: string) => ["runs", id] as const,
    runWithValues: (id: string) => ["runs", id, "values"] as const,
    runRuntime: (id: string) => ["runs", id, "runtime"] as const,
    accountPreferences: ["account", "preferences"] as const,
    workflowMode: (workflowId: string) => ["workflows", workflowId, "mode"] as const,
    collections: (tenantId: string) => ["collections", tenantId] as const,
    collection: (tenantId: string, collectionId: string) => ["collections", tenantId, collectionId] as const,
    collectionFields: (tenantId: string, collectionId: string) => ["collections", tenantId, collectionId, "fields"] as const,
    collectionRecords: (tenantId: string, collectionId: string) => ["collections", tenantId, collectionId, "records"] as const,
    collectionRecord: (tenantId: string, collectionId: string, recordId: string) => ["collections", tenantId, collectionId, "records", recordId] as const,
    dataSources: ["dataSources"] as const,
    workflowDataSources: (workflowId: string) => ["workflows", workflowId, "dataSources"] as const,
    dataSource: (id: string) => ["dataSources", id] as const,
    logicRules: (workflowId: string) => ["workflows", workflowId, "logicRules"] as const,
    templateValidation: (templateId: string, workflowId: string) =>
        ["templates", templateId, "validation", workflowId] as const,
};
