-- Migration: Add run_generated_documents table
-- Purpose: Track documents generated during workflow completion
-- Date: 2025-11-26
--
-- Stores references to documents generated by Final Documents blocks

CREATE TABLE IF NOT EXISTS run_generated_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id UUID NOT NULL REFERENCES workflow_runs(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  file_url TEXT NOT NULL,
  mime_type TEXT,
  file_size INTEGER,
  template_id UUID REFERENCES workflow_templates(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  CONSTRAINT run_generated_documents_run_id_idx_check CHECK (run_id IS NOT NULL)
);

-- Add indices for performance
CREATE INDEX IF NOT EXISTS run_generated_documents_run_id_idx ON run_generated_documents(run_id);
CREATE INDEX IF NOT EXISTS run_generated_documents_created_at_idx ON run_generated_documents(created_at);

-- Add comments for documentation
COMMENT ON TABLE run_generated_documents IS 'Stores documents generated during workflow completion';
COMMENT ON COLUMN run_generated_documents.run_id IS 'Reference to the workflow run';
COMMENT ON COLUMN run_generated_documents.file_name IS 'Display name of the generated document';
COMMENT ON COLUMN run_generated_documents.file_url IS 'Public or signed URL to download the document';
COMMENT ON COLUMN run_generated_documents.mime_type IS 'MIME type of the document (e.g., application/vnd.openxmlformats-officedocument.wordprocessingml.document)';
COMMENT ON COLUMN run_generated_documents.file_size IS 'Size of the document in bytes';
COMMENT ON COLUMN run_generated_documents.template_id IS 'Reference to the template used to generate the document';
