
export interface VariableLineage {
    variableName: string;
    createdByBlockId: string;
    createdAtStep: number;
    sourceType:
    | 'question'
    | 'query'
    | 'js'
    | 'compute'
    | 'transform'
    | 'loop'
    | 'writeResult'
    | 'externalResult'
    | 'system'; // for input/initial vars
    inputVariables?: string[];
}

export interface ListLineage {
    listName: string;
    queryId: string; // The ID of the QueryBlock
    tableId: string;
    filters: Array<{
        columnId: string;
        operator: string;
        value: any;
    }>;
    sort?: Array<{
        columnId: string;
        direction: 'asc' | 'desc';
    }>;
}

export interface ExecutionStep {
    stepNumber: number;
    blockId: string;
    blockType: string;
    timestamp: Date;
    status: 'executed' | 'skipped' | 'error';
    skippedReason?: string;
    inputs: Record<string, any>; // Resolved input values
    outputs: Record<string, any>; // Execution results
    error?: string;

    // Side effects info
    sideEffects?: {
        writes?: Record<string, any>;
        externalSends?: Record<string, any>;
    };

    // Lineage info generated by this step
    lineage?: VariableLineage[];

    // Performance metrics
    durationMs?: number;
    metrics?: {
        dbTimeMs?: number;
        jsTimeMs?: number;
        [key: string]: number | undefined;
    };
}

export interface WorkflowTrace {
    executionId: string;
    workflowId: string;
    workflowVersionId: string;
    startTime: Date;
    endTime?: Date;
    status: 'success' | 'error';
    steps: ExecutionStep[];
    variableLineage: Record<string, VariableLineage>;
    listLineage: Record<string, ListLineage>;

    // Global metrics
    metrics?: {
        totalDurationMs: number;
        totalDbTimeMs?: number;
        totalJsTimeMs?: number;
        queryCount?: number;
        executionMode: 'live' | 'preview' | 'snapshot';
    };
}
