import { nanoid } from 'nanoid';
import { v4 as uuidv4 } from 'uuid';

import type { Workflow, WorkflowVersion, Run } from '../../shared/schema';

/**
 * Graph Factory
 * Helpers to create valid Graph-based Workflows and Runs for testing.
 *
 * NOTE: The visual graph engine (server/engine) has been removed. These local
 * type shims preserve the legacy graphJson fixture shape still used by the
 * analytics and snapshot integration tests, without depending on engine code.
 */
interface QuestionNodeConfig {
    key: string;
    question?: string;
    [key: string]: unknown;
}

interface Node {
    id: string;
    type: string;
    config: Record<string, unknown>;
}

interface GraphJson {
    nodes: Node[];
    edges: Array<{ id: string; source: string; target: string }>;
    startNodeId: string;
}

export const createNodeId = (prefix: string = 'node') => `${prefix}_${nanoid(6)}`;

export function createQuestionNode(
    id: string,
    question: string,
    type: 'short_text' | 'yes_no' | 'multiple_choice' = 'short_text',
    options: Record<string, unknown> = {}
): Node {
    return {
        id,
        type: 'question',
        // @ts-ignore - TODO: fix type
        config: {
            key: id,
            question,
            
            ...options,
        } as QuestionNodeConfig,
    };
}

export function createGraph(nodes: Node[] = []): GraphJson {
    if (nodes.length === 0) {
        const startNode = createQuestionNode('start', 'Start Question');
        nodes.push(startNode);
    }

    // Auto-generate edges for a simple linear flow if no edges provided
    // This is a simplification for basic tests
    const edges = [];
    for (let i = 0; i < nodes.length - 1; i++) {
        edges.push({
            id: `edge_${i}`,
            source: nodes[i].id,
            target: nodes[i + 1].id,
        });
    }

    return {
        nodes,
        edges,
        startNodeId: nodes[0].id,
    };
}

export function createGraphWorkflow(
    overrides: Partial<Workflow> = {},
    graphOverrides: Partial<GraphJson> = {}
): { workflow: Workflow; version: WorkflowVersion } {
    const workflowId = uuidv4();
    const versionId = uuidv4();
    const now = new Date();

    const overridesAny = overrides as Record<string, unknown>;
    const creatorId = overridesAny.createdBy as string ?? overridesAny.creatorId as string ?? uuidv4();
    const ownerId = overridesAny.ownerId as string ?? creatorId;

    const workflow: Workflow = {
        id: workflowId,
        projectId: uuidv4(),
        title: overrides.title ?? overridesAny.name as string ?? 'Test Graph Workflow',
        description: 'Generated by graphFactory',
        creatorId,
        ownerId,
        createdAt: now,
        updatedAt: now,
        ...overrides,
    } as Workflow;

    // Remove invalid keys if they leaked in from overrides
    delete (workflow as Record<string, unknown>).name;
    delete (workflow as Record<string, unknown>).status;

    const graph = createGraph(graphOverrides.nodes);

    const version: WorkflowVersion = {
        id: versionId,
        workflowId: workflowId,
        graphJson: graph,
        versionNumber: 1,
        isDraft: true,
        createdBy: creatorId,
        createdAt: now,
        updatedAt: now,
        published: false,
    } as WorkflowVersion;

    return { workflow, version };
}

export function createGraphRun(
    workflowVersionId: string,
    overrides: Partial<Run> = {}
): Run {
    return {
        id: uuidv4(),
        workflowVersionId,
        status: 'pending',
        state: {
            currentNodeId: 'start',
            history: [],
            values: {},
        },
        createdAt: new Date(),
        updatedAt: new Date(),
        ...overrides,
    } as Run;
}
