import { v4 as uuidv4 } from 'uuid';
import { nanoid } from 'nanoid';
import type { GraphJson } from '../../server/engine/validate';
import type { Node, NodeType } from '../../server/engine/registry';
import type { QuestionNodeConfig } from '../../server/engine/nodes/question';
import type { Workflow, WorkflowVersion, Run } from '../../shared/schema';

/**
 * Graph Factory
 * Helpers to create valid Graph-based Workflows and Runs for testing.
 */

export const createNodeId = (prefix: string = 'node') => `${prefix}_${nanoid(6)}`;

export function createQuestionNode(
    id: string,
    question: string,
    type: 'short_text' | 'yes_no' | 'multiple_choice' = 'short_text',
    options: any = {}
): Node {
    return {
        id,
        type: 'question',
        config: {
            key: id,
            question,
            type,
            ...options,
        } as QuestionNodeConfig,
    };
}

export function createGraph(nodes: Node[] = []): GraphJson {
    if (nodes.length === 0) {
        const startNode = createQuestionNode('start', 'Start Question');
        nodes.push(startNode);
    }

    // Auto-generate edges for a simple linear flow if no edges provided
    // This is a simplification for basic tests
    const edges = [];
    for (let i = 0; i < nodes.length - 1; i++) {
        edges.push({
            id: `edge_${i}`,
            source: nodes[i].id,
            target: nodes[i + 1].id,
        });
    }

    return {
        nodes,
        edges,
        startNodeId: nodes[0].id,
    };
}

export function createGraphWorkflow(
    overrides: Partial<Workflow> = {},
    graphOverrides: Partial<GraphJson> = {}
): { workflow: Workflow; version: WorkflowVersion } {
    const workflowId = uuidv4();
    const versionId = uuidv4();
    const now = new Date();

    const creatorId = (overrides as any).createdBy || (overrides as any).creatorId || uuidv4();
    const ownerId = (overrides as any).ownerId || creatorId;

    const workflow: Workflow = {
        id: workflowId,
        projectId: uuidv4(),
        title: overrides.name || 'Test Graph Workflow', // Legacy title
        name: 'Test Graph Workflow',
        description: 'Generated by graphFactory',
        creatorId,
        ownerId,
        status: 'draft',
        createdAt: now,
        updatedAt: now,
        ...overrides,
    } as any;

    const graph = createGraph(graphOverrides.nodes);

    const version: WorkflowVersion = {
        id: versionId,
        workflowId: workflowId,
        graphJson: graph,
        version: 1,
        status: 'draft',
        createdBy: creatorId,
        createdAt: now,
        updatedAt: now,
    } as any;

    return { workflow, version };
}

export function createGraphRun(
    workflowVersionId: string,
    overrides: Partial<Run> = {}
): Run {
    return {
        id: uuidv4(),
        workflowVersionId,
        status: 'pending',
        state: {
            currentNodeId: 'start',
            history: [],
            values: {},
        },
        createdAt: new Date(),
        updatedAt: new Date(),
        ...overrides,
    } as any;
}
